"""
Constants
"""
# Variables for Pygame
BOARD_WIDTH = 30
BOARD_HEIGHT = 20
PIXEL_SIZE = 20
GAP_SIZE = 5

# Pygame window
BACKGROUND_COLOUR = 7, 7, 7
WINDOW_HEIGHT = (PIXEL_SIZE + GAP_SIZE) * BOARD_HEIGHT
WINDOW_WIDTH = (PIXEL_SIZE + GAP_SIZE) * BOARD_WIDTH
RUNNING_WINDOW = True
